env:
  browser: true
  commonjs: true
  es2021: true
extends:
  [
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
    'plugin:@typescript-eslint/recommended'
  ]
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures: { jsx: false }
rules: {
    # useful to have in node.js,
    # if you're sure you don't need to handle error, rename it to "_err"
    handle-callback-err: 2,

    # just to make sure we don't forget to remove them when releasing
    no-debugger: 2,

    # add "falls through" for those
    no-fallthrough: 2,

    # just warnings about whitespace weirdness here
    eol-last: 1,
    no-irregular-whitespace: 1,
    no-mixed-spaces-and-tabs: [1, smart-tabs],
    no-trailing-spaces: 1,

    # probably always an error, tell me if it's not
    no-new-require: 2,

    # single most important rule here, without it linting won't even
    # make any sense
    no-undef: 2,

    # in practice, those are always errors
    no-unreachable: 2,

    # useful for code clean-up
    no-unused-vars: [1, { 'vars': 'all', 'args': 'none' }],

    no-console: 2,

    new-cap: 0,
    max-len: [2, 150, 4],
    space-before-function-paren:
      [
        'error',
        { 'anonymous': 'never', 'named': 'never', 'asyncArrow': 'ignore' }
      ]
  }
