#-------------------------------------------------------------------------------
# NodeserverTS Copyright © 2022 rvnrstnsyh All Rights Reserved
#-------------------------------------------------------------------------------
#
# Author    : Rivane Rasetiansyah <re@rvnrstnsyh.dev> (https://rvnrstnsyh.dev)
# GitHub    : https://github.com/rvnrstnsyh
# GitLab    : https://gitlab.com/rvnrstnsyh
#

POST http://localhost:3000/api/user/v1/register
Content-Type: application/json

{
	"username": "johntheripper",
	"email": "hello@johntheripper.dev",
	"password": "secret123"
}

###

POST http://localhost:3000/api/user/v1/login
Content-Type: application/json

{
	"email": "hello@johntheripper.dev",
	"password": "secret123"
}

###

GET http://localhost:3000/api/user/v1
# Authorization: Bearer <access_token>
