#-------------------------------------------------------------------------------
# NodeserverTS Copyright © 2022 rvnrstnsyh All Rights Reserved
#-------------------------------------------------------------------------------
#
# Author    : Rivane Rasetiansyah <re@rvnrstnsyh.dev> (https://rvnrstnsyh.dev)
# GitHub    : https://github.com/rvnrstnsyh
# GitLab    : https://gitlab.com/rvnrstnsyh
#

POST http://localhost:3000/api/post
Content-Type: application/json

{
	"title": "Back-End node server",
	"body": "This is the first book"
}
