#-------------------------------------------------------------------------------
# NodeserverTS Copyright © 2022 rvnrstnsyh All Rights Reserved
#-------------------------------------------------------------------------------
#
# Author    : Rivane Rasetiansyah <re@rvnrstnsyh.dev> (https://rvnrstnsyh.dev)
# GitHub    : https://github.com/rvnrstnsyh
# GitLab    : https://gitlab.com/rvnrstnsyh
#

POST http://localhost:3000/api/user/v1/register
# Authorization: Basic <base64>
Content-Type: application/json

{
	"username": "williamrosenberg",
	"email": "dunkin@donuts.dev",
	"password": "henlloworlf!"
}

###
POST http://localhost:3000/api/user/v1/login
# Authorization: Basic <base64>
Content-Type: application/json

{
	"email": "dunkin@donuts.dev",
	"password": "henlloworlf!"
}

###
GET http://localhost:3000/api/user/v1/verify
# Authorization: Basic <base64>
